config/routes.rb
HappyTracker::Application.routes.draw do
 

  resources :happiness_entries

  resources :users

  root :to => "static_pages#home"
  get "/help" => "static_pages#help"

  resources :incoming_mails

end

app/models/happiness_entry.rb
# == Schema Information
#
# Table name: happiness_entries
#
#  id          :integer          not null, primary key
#  score       :integer
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class HappinessEntry < ActiveRecord::Base
  attr_accessible :description, :score, :user_id
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email
  has_many :happiness_entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/happiness_entries_controller.rb
class HappinessEntriesController < ApplicationController
  # GET /happiness_entries
  # GET /happiness_entries.json
  def index
    @happiness_entries = HappinessEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @happiness_entries }
    end
  end

  # GET /happiness_entries/1
  # GET /happiness_entries/1.json
  def show
    @happiness_entry = HappinessEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @happiness_entry }
    end
  end

  # GET /happiness_entries/new
  # GET /happiness_entries/new.json
  def new
    @happiness_entry = HappinessEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @happiness_entry }
    end
  end

  # GET /happiness_entries/1/edit
  def edit
    @happiness_entry = HappinessEntry.find(params[:id])
  end

  # POST /happiness_entries
  # POST /happiness_entries.json
  def create
    @happiness_entry = HappinessEntry.new(params[:happiness_entry])

    respond_to do |format|
      if @happiness_entry.save
        format.html { redirect_to @happiness_entry, notice: 'Happiness entry was successfully created.' }
        format.json { render json: @happiness_entry, status: :created, location: @happiness_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @happiness_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /happiness_entries/1
  # PUT /happiness_entries/1.json
  def update
    @happiness_entry = HappinessEntry.find(params[:id])

    respond_to do |format|
      if @happiness_entry.update_attributes(params[:happiness_entry])
        format.html { redirect_to @happiness_entry, notice: 'Happiness entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @happiness_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /happiness_entries/1
  # DELETE /happiness_entries/1.json
  def destroy
    @happiness_entry = HappinessEntry.find(params[:id])
    @happiness_entry.destroy

    respond_to do |format|
      format.html { redirect_to happiness_entries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/incoming_mails_controller.rb
class IncomingMailsController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def create

  	puts "received email, in the create controller"
  	#puts "reply_plain: \n#{params[:reply_plain]}"

  	#extract happiness entry id
  	entry_id = /.*\+([0-9]+)@/.match(params[:envelope][:to])[1]

    entry_to_update = HappinessEntry.find(entry_id)

    reply_plain = params[:reply_plain]

    #parse out score
    reply_plain_matches = /^([0-9]+)\.(.*)/.match(reply_plain)
    
    entry_to_update.score = "#{reply_plain_matches[1]}"
	entry_to_update.description = "#{reply_plain_matches[2]}"


    # Do some other stuff with the mail message

    if entry_to_update.save
      render :text => 'Success', :status => 200
    else
      render :text => message.errors.full_messages, :status => 422, :content_type => Mime::TEXT.to_s
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
require 'mandrill'

class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def self.send_happiness_emails
    puts "sending happiness emails..."
    #m = Mandrill::API.new('xOiHqFbCRGjYDk9I1D1p_g')
    m = Mandrill::API.new

    all_users = User.all()
    all_users.each do |user|
    
      todays_date = Time.now().strftime("%A, %B %d, %Y")

      new_entry = HappinessEntry.create(user_id: user.id)

      #send email to user
      message = {
       :subject=> "[HappinessTracker] #{todays_date}: How happy were you today?",
       :from_name=> "HappinessTracker",
       :text=>"Hi there, First, on a scale of 1-10, with 10 being happiest, what was your happiness score today? Second, describe in a few sentences or a paragraph, what made you feel that way?",
       :to=>[
         {
           :email=> "#{user.email}"
         }
       ],
       :html=>"<html><h1>Hi there,</h1><p>First, on a scale of 1-10, with 10 being happiest, what was your happiness score today?</p><p>Second, describe in a few sentences or a paragraph, what made you feel that way?</p></html>",
       :from_email=>"1c8b3e27f70587dbda6b+#{new_entry.id}@cloudmailin.net"
      }
      m.messages.send message
      puts "sent email to #{user.email}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/happiness_entries_helper.rb
module HappinessEntriesHelper
end

app/helpers/incoming_mails_helper.rb
module IncomingMailsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/happiness_entries/_form.html.erb
<%= form_for(@happiness_entry) do |f| %>
  <% if @happiness_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@happiness_entry.errors.count, "error") %> prohibited this happiness_entry from being saved:</h2>

      <ul>
      <% @happiness_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/happiness_entries/edit.html.erb
<h1>Editing happiness_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @happiness_entry %> |
<%= link_to 'Back', happiness_entries_path %>

app/views/happiness_entries/index.html.erb
<h1>Listing happiness_entries</h1>

<table>
  <tr>
    <th>Score</th>
    <th>Description</th>
    <th>User id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @happiness_entries.each do |happiness_entry| %>
  <tr>
    <td><%= happiness_entry.score %></td>
    <td><%= happiness_entry.description %></td>
    <td><%= happiness_entry.user_id %></td>
    <td><%= link_to 'Show', happiness_entry %></td>
    <td><%= link_to 'Edit', edit_happiness_entry_path(happiness_entry) %></td>
    <td><%= link_to 'Destroy', happiness_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Happiness entry', new_happiness_entry_path %>

app/views/happiness_entries/new.html.erb
<h1>New happiness_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', happiness_entries_path %>

app/views/happiness_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Score:</b>
  <%= @happiness_entry.score %>
</p>

<p>
  <b>Description:</b>
  <%= @happiness_entry.description %>
</p>

<p>
  <b>User id:</b>
  <%= @happiness_entry.user_id %>
</p>



<%= link_to 'Edit', edit_happiness_entry_path(@happiness_entry) %> |
<%= link_to 'Back', happiness_entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
  <title>HappinessTracker | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div id="main_header">Track your happiness</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>